# Generated by Django 5.1.6 on 2025-02-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usersessionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
